version: '2'

services:
  web:
    image: "transempregos-portal:${IMAGE_VERSION}"
    environment:
      NODE_ENV: production
      MONGO_URI: "${MONGO_URI}"
    ports:
      - 80:3000
    command: node dist/server/bin/www.js